Add dynamic collection parameter introspection
In the event Task#collection returns a callable object which fails to
accept a cursor: keyword argument, a rather unhelpful error is raised:

    ArgumentError (wrong number of arguments (given 1, expected 0))

At the extra cost of having to introspect the parameters of the
callable, we can check if it will accept the cursor: keyword argument,
and provide a more helpful error message.

Note that we must handle the cases of the callable being a wrapper vs a
Plain-Old-Ruby-Object responding to .call differently:

- Wrapper objects (like instance of Proc, Proc (lambda), and Method)
  have a .call method which accepts any arguments and forwards them to
  the wrapped code. For this, we must check their .parameters directly.

  ```ruby
  -> { }.parameters               # []
  -> { }.method(:call).parameters # [[:rest]]
  -> { }.call(cursor: 123)        # wrong number of arguments (given 1, expected 0) (ArgumentError)
  ```

- For other object (not responding to .parameters directly), we can
  check their method(:call).parameters instead.

  ```ruby
  class CursorlessCallable
    def call
    end
  end
  CursorlessCallable.new.parameters               # undefined method `parameters' for #<CursorlessCallable:0xXXXXXXXXXXXXXXXX> (NoMethodError)
  CursorlessCallable.new.method(:call).parameters # []
  CursorlessCallable.new.call(cursor: 123)        # wrong number of arguments (given 1, expected 0) (ArgumentError)
  ```

Unfortunately, we can't do anything about cases of outright delegation,
since without a type system, problems only arise when we .call them.

  ```ruby
  class DelegatedCallable < CursorlessCallable
    def call(...)
      super
    end
  end
  DelegatedCallable.new.parameters               # undefined method `parameters' for #<DelegatedCallable:0xXXXXXXXXXXXXXXXX> (NoMethodError)
  DelegatedCallable.new.method(:call).parameters # [[:rest, :*], [:block, :&]]
  DelegatedCallable.new.call(cursor: 123)        # wrong number of arguments (given 1, expected 0) (ArgumentError)
  ```